//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllStocked
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLogin
    {
        public int LoginID { get; set; }
        public int AccountID { get; set; }
        public string Password { get; set; }
        public string Hash { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string RecoveryKey { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
