//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllStocked
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AllStockedDBEntities : DbContext
    {
        public AllStockedDBEntities()
            : base("name=AllStockedDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<AccountType> AccountTypes { get; set; }
        public DbSet<SecondaryAccountAccess> SecondaryAccountAccesses { get; set; }
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AccountStatu> AccountStatus { get; set; }
    }
}
